version: '3'
services:
  telegram:
    build: .
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: always