name: publish

on:
  push:
    tags:
      - "*"
env:
  PROJECT_NAME: "XinjingdailyBot.WebAPI"
  CONFIGURATION: Release
  DOTNET_NOLOGO: true
  DOTNET_SDK_VERSION: 7.0.x


jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch:
          [
            win-x64,
            win-arm64,
            osx-x64,
            osx-arm64,
            linux-x64,
            linux-arm,
            linux-arm64,
            generic,
          ]

    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2
        with:
          submodules: recursive

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2.1.0
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: Verify .NET Core
        run: dotnet --info

      - name: Prepare for publishing ${{ env.PROJECT_NAME }}
        shell: pwsh
        run: |
          dotnet restore
          dotnet build ${{ env.PROJECT_NAME }} -c "$env:CONFIGURATION" -p:ContinuousIntegrationBuild=true -p:TargetLatestRuntimePatch=false -p:UseAppHost=false --no-restore --nologo

      - name: Publish ${{ env.PROJECT_NAME }} ${{ matrix.arch }}
        shell: pwsh
        run: |
          $variant = '${{ matrix.arch }}'

          $commonArgs = '-p:PublishSingleFile=true', '-p:IncludeNativeLibrariesForSelfExtract=true', '-p:PublishTrimmed=true'

          if ($variant -eq 'generic') {
            $buildArgs = '-p:TargetLatestRuntimePatch=false', '-p:UseAppHost=false'
          } else {
            $buildArgs = '-r', "$variant", '--self-contained'
          }

          dotnet publish ${{ env.PROJECT_NAME }} -c "$env:CONFIGURATION" -o "./tmp/${{ env.PROJECT_NAME }}" -p:XJBVariant="$variant" -p:ContinuousIntegrationBuild=true --no-restore --nologo $commonArgs $buildArgs

      - name: Zip files
        run: 7z a -bd -slp -tzip -mm=Deflate -mx=5 -mfb=150 -mpass=10 "./dist/${{ matrix.arch }}.zip" "./tmp/${{ env.PROJECT_NAME }}/*"

      - name: Upload ${{ env.PROJECT_NAME }} ${{ matrix.arch }}
        continue-on-error: true
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ${{ matrix.arch }}
          path: ./dist/${{ matrix.arch }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.0.2

      - name: Download win-x64 artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: win-x64
          path: out

      - name: Download win-arm64 artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: win-arm64
          path: out

      - name: Download osx-x64 artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: osx-x64
          path: out

      - name: Download osx-arm64 artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: osx-arm64
          path: out

      - name: Download linux-x64 artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: linux-x64
          path: out

      - name: Download linux-arm artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: linux-arm
          path: out

      - name: Download linux-arm64 artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: linux-arm64
          path: out

      - name: Download generic artifact
        uses: actions/download-artifact@v3.0.0
        with:
          name: generic
          path: out

      - name: Create ${{ env.PROJECT_NAME }} GitHub release
        id: github_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ env.PROJECT_NAME }} ${{ github.ref }}
          body: release created bt github actions
          prerelease: true

      - name: Upload win-x64 to GitHub release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: out/win-x64.zip
          asset_name: ${{ env.PROJECT_NAME }}-win-x64.zip
          asset_content_type: application/zip

      - name: Upload win-arm64 to GitHub release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: out/win-arm64.zip
          asset_name: ${{ env.PROJECT_NAME }}-win-arm64.zip
          asset_content_type: application/zip

      - name: Upload osx-x64 to GitHub release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: out/osx-x64.zip
          asset_name: ${{ env.PROJECT_NAME }}-osx-x64.zip
          asset_content_type: application/zip

      - name: Upload osx-arm64 to GitHub release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: out/osx-arm64.zip
          asset_name: ${{ env.PROJECT_NAME }}-osx-arm64.zip
          asset_content_type: application/zip

      - name: Upload linux-x64 to GitHub release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: out/linux-x64.zip
          asset_name: ${{ env.PROJECT_NAME }}-linux-x64.zip
          asset_content_type: application/zip

      - name: Upload linux-arm to GitHub release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: out/linux-arm.zip
          asset_name: ${{ env.PROJECT_NAME }}-linux-arm.zip
          asset_content_type: application/zip

      - name: Upload linux-arm64 to GitHub release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: out/linux-arm64.zip
          asset_name: ${{ env.PROJECT_NAME }}-linux-arm64.zip
          asset_content_type: application/zip

      - name: Upload generic to GitHub release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.github_release.outputs.upload_url }}
          asset_path: out/generic.zip
          asset_name: ${{ env.PROJECT_NAME }}-generic.zip
          asset_content_type: application/zip
